# Generated by Django 4.2.4 on 2023-08-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountConfig', '0002_user_is_active_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
