# Generated by Django 4.2.4 on 2023-08-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('distance', models.FloatField()),
                ('fromCoordinatesLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fromCoordinatesLong', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
